meta_product_name: "College Sports Authority"
meta_title: "College Sports Authority - Bolsas para atletas nos EUA"
meta_description: "Assessoria a estudantes-atletas para os processos seletivos de universidades dos Estados Unidos"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards